### ISSUE TITLE
no such file to load -- puppet/provider/regpowershell

### ISSUE THREAD

**Issue by jadestorm** [ipcrm/registry_acl#3]
Howdy!  I'm trying to make use of this module but I'm getting a failure to load the regpowershell.rb component.  Before I copy/paste the message, few things about my environment:

- Windows Server 2016 puppet node
- RHEL7 Puppet servers
- Puppet 4 (1.10.4 of puppet-agent)

The message is:
```
puppet : [1;31mError: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload 
puppet/type/reg_acl: Could not autoload puppet/provider/reg_acl/regacl: no such file to load -- puppet/provider/regpowershell at 
```

**Comment by jadestorm** [comment]
Any ideas what might be going?  I see regpowershell.rb in modules/registry_acl/lib/puppet/provider

**Comment by jadestorm** [comment]
I see you are doing basically exactly the same thing as what the puppetlabs firewall module does for that require.  So imo there is no rhyme or reason to why it is failing.  If you don't end up having an idea off the top of your head though (and/or haven't seen this yet) -- I may end up having a PR waiting for you if I can figure out what it's on about.  =)

**Comment by ipcrm** [comment]
Hi @jadestorm - So I've not tested this on 2016; so thanks for being a beta tester :).  Trying to get my hands on a 2016 instance so I can recreate.

**Comment by jadestorm** [comment]
=)  So after doing some more diving into it I've found the issue.  Thankfully it is not related to server 2016 -- it's actually related to me Linux puppet masters.  Basically since I'm using r10k with my puppet setup, I need to run puppet generate types to make sure things map properly.  When it goes to map reg_acl, it gets an error because the puppet masters have no idea what win32/ is.  I'm building a fix that I'm not fully pleased with, but it does seem to be resolving the issue!  I'll send up a PR when I'm done testing it.  =)

**Comment by ipcrm** [comment]
#4 Should resolve this.  Thx @jadestorm!
