### ISSUE TITLE
Unresolvable SID

### ISSUE THREAD

**Issue by bwilcox** [ipcrm/registry_acl#8]
I'm in a situation where I have to set some ACLs for a registry object that pre-exists.  At some point in time there was an ACL already applied but the user for that ACL has since been removed, leaving an ACL with a SID that is unresolvable.  I created a pull request with what fixes my problem by ignoring existing rules with unresolvable SIDs.  

I'm unsure if this is the best way to resolve the problem.

**Comment by ipcrm** [comment]
#7 was opened for this.

@bwilcox I think that's probably the best approach; at least that situation will be logged and the rest of the desired state gets applied.

**Comment by ipcrm** [comment]
merged.
